# Generated by Django 4.1.4 on 2022-12-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jobs",
            new_name="Job",
        ),
        migrations.RenameField(
            model_name="candidateskill",
            old_name="skills_name",
            new_name="skill_name",
        ),
        migrations.RenameField(
            model_name="jobskill",
            old_name="skills_name",
            new_name="skill_name",
        ),
    ]
