# Generated by Django 4.1.4 on 2022-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_rename_jobs_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateskill",
            name="skill_name",
            field=models.CharField(max_length=120),
        ),
    ]
